ExerciseDB/Controllers/ExerciseController.cs
using System.Collections;
using ExerciseDB.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Globalization;

namespace ExerciseDB.Controllers;

// Controller responsible for handling exercise search via external API and returning results to views or JavaScript.
public class ExerciseController : Controller
{
    private readonly ApiService _apiService;

    public ExerciseController(ApiService apiService)
    {
        _apiService = apiService;
    }


    // Sends search requests to an external exercise API, formats results, and returns them to the view.
    public async Task<IActionResult> Index(string searchTerm)
    {
        if (string.IsNullOrEmpty(searchTerm))
        {
            return View();
        }
        var textInfo = new CultureInfo("en-US").TextInfo; // Used to capitalize each word in exercise names
        
        var jsonResponse= await _apiService.SearchExercisesAsync(searchTerm);
        Console.WriteLine($"API Response: {jsonResponse}");
        
        var exercises = JsonConvert.DeserializeObject<List<Exercise>>(jsonResponse);
        
        foreach (var exercise in exercises)
        {
            exercise.Name = textInfo.ToTitleCase(exercise.Name); // Used to capitalize each word in the exercise name
        }
        
        return View(exercises);
    }

    
    // Called via JavaScript for live search. Sends a request to an external API and returns matching exercises as JSON.
    public async Task<IActionResult> LiveSearch(string searchTerm)
    {
        if (string.IsNullOrEmpty(searchTerm))
        {
            return Json(new List<Exercise>()); // returns empty Json to JS
        }
        var textInfo = new CultureInfo("en-US").TextInfo;
        
        var jsonResponse = await _apiService.SearchExercisesAsync(searchTerm);
        Console.WriteLine($"API Live Search Response: {jsonResponse}");
        
        var exercises = JsonConvert.DeserializeObject<List<Exercise>>(jsonResponse);
        
        foreach (var exercise in exercises)
        {
            exercise.Name = textInfo.ToTitleCase(exercise.Name);
        }
        
        return Json(exercises);
    }
    
}

ExerciseDB/Controllers/WorkoutController.cs
using System.Security.Claims;
using ExerciseDB.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace ExerciseDB.Controllers;

// Controller responsible for handling workout-related views and actions, including create, read, update, and delete operations.
[Authorize]
public class WorkoutController : Controller
{
    private readonly IWorkoutRepository repo;
    private readonly HttpClient _client;
    private readonly string _apiKey;
    private readonly UserManager<IdentityUser> _userManager;


    private string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier);
    
    public WorkoutController(IWorkoutRepository repo)
    {
        this.repo = repo;
    }

    
    // Displays a list of all workouts, optionally sorted and/or filtered by a search string.
    public IActionResult Index(string sortBy, string searchString)
    {
        var workouts = repo.GetAllWorkouts(sortBy, searchString, UserId);
        return View(workouts);
    }
    
    
    // Displays details for a single workout, including its sets.
    public IActionResult ViewWorkout(int id)
    {
        var workout = repo.GetWorkout(id, UserId);
        return View(workout);
    }

    
    // Loads the update form for a specific workout by ID.
    public IActionResult UpdateWorkout(int id)
    {
        Workout workout = repo.GetWorkout(id, UserId);
        if (workout == null)
        {
            return NotFound();
        }
        return View(workout);
    }

    // Handles form submission for workout updates, including updating and/or deletion of sets.
    public IActionResult UpdateWorkoutToDatabase(Workout workout, List<int> DeletedSetIds)
    {
        Console.WriteLine("WorkoutId received from form: " + workout.WorkoutId);
        if (workout.Sets == null)
        {
            Console.WriteLine("No sets received.");
        }
        else
        {
            Console.WriteLine("Number of sets: " + workout.Sets.Count);
        }

        // Delete sets that the user marked for removal:
        if (DeletedSetIds != null && DeletedSetIds.Any())
        {
            foreach (var id in DeletedSetIds)
            {
                repo.DeleteSet(id, UserId);
            }
        }

        repo.UpdateWorkout(workout, UserId);
        return RedirectToAction("ViewWorkout", new { id = workout.WorkoutId });
    }

    // Loads the form for creating a new workout, optionally pre-filling the exercise name.
    public IActionResult CreateWorkout(string exerciseName)
    {
        var workout = new Workout();
        
        // Passes selected exercise name to the view, for pre-filling the exercise name field:
        if (exerciseName != null)
        {
            workout.ExerciseName = exerciseName;
        }

        return View(workout);
    }
    
    // Handles form submission to create a new workout and its sets in the database.
    public IActionResult CreateWorkoutToDataBase(Workout workoutToCreate)
    {
   
        repo.CreateWorkout(workoutToCreate, UserId);
        return RedirectToAction("Index");
    }

    // Deletes a workout and redirects to the index view.
    public IActionResult DeleteWorkout(int id)
    {
        repo.DeleteWorkout(id, UserId);
        return RedirectToAction("Index");
    }
    
}

ExerciseDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FitnessTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/ExerciseDB.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    @if (ViewBag.HideNavbar != true)
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light sticky-top bg-white">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fitness Tracker</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercise" asp-action="Index">Find an Exercise</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Workout" asp-action="Index">Workouts</a>
                        </li>
                    </ul>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark me-2" asp-controller="Account" asp-action="Login"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5.52 19c.64-2.2 1.84-3 3.22-3h6.52c1.38 0 2.58.8 3.22 3"/><circle cx="12" cy="10" r="3"/><circle cx="12" cy="12" r="10"/></svg> Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Register"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><line x1="20" y1="8" x2="20" y2="14"></line><line x1="23" y1="11" x2="17" y2="11"></line></svg> Register</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item nav-link text-dark">
                                @User.Identity.Name
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                                    <button type="submit" class="btn btn-link nav-link text-dark">Logout</button>
                                </form>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    }
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted mt-auto">
    <div class="container">
        &copy; 2025 - Fitness Tracker
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>